name: flattener
description: A CLI tool to flatten directory structures
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  lints: ^4.0.0

executables:
  flattener: flattener